// Sample data for realistic listings
export const categories = {
  Electronics: [
    { title: "iPhone 13 Pro Max - 256GB", price: "799", condition: "excellent", description: "Barely used iPhone 13 Pro Max in Sierra Blue. Includes original box, charger, and case. Battery health at 98%. No scratches or dents." },
    { title: "MacBook Air M1 - 8GB RAM", price: "850", condition: "good", description: "2020 MacBook Air with M1 chip. Great for students and professionals. Minor wear on keyboard. Comes with original charger." },
    { title: "Samsung Galaxy S22 Ultra", price: "699", condition: "excellent", description: "Unlocked Samsung Galaxy S22 Ultra with S Pen. 512GB storage. Phantom Black. Screen protector and case included." },
    { title: "iPad Pro 11-inch 2021", price: "650", condition: "like-new", description: "iPad Pro with M1 chip, 128GB. Space Gray. Includes Magic Keyboard and Apple Pencil 2nd gen." },
    { title: "Sony WH-1000XM4 Headphones", price: "249", condition: "good", description: "Premium noise-canceling headphones. Black color. All accessories included. Works perfectly." },
    { title: "Nintendo Switch OLED", price: "299", condition: "excellent", description: "White OLED model with extra joy-cons. Includes 5 games: Mario Kart, Zelda, Animal Crossing, Smash Bros, Pokemon." },
    { title: "Dell XPS 15 Laptop", price: "1200", condition: "good", description: "15.6\" 4K display, Intel i7-11800H, 16GB RAM, 512GB SSD, RTX 3050 Ti. Perfect for creative work." },
    { title: "Canon EOS R6 Camera Body", price: "1899", condition: "excellent", description: "Professional mirrorless camera. Low shutter count (2,500). Includes 2 batteries and charger." },
    { title: "Apple Watch Series 7 - 45mm", price: "329", condition: "like-new", description: "GPS + Cellular. Midnight aluminum. Includes original band and charging cable. AppleCare+ until 2025." },
    { title: "Bose SoundLink Revolve+", price: "179", condition: "good", description: "Portable Bluetooth speaker with 360-degree sound. Triple Black. 16-hour battery life." },
    { title: "GoPro Hero 11 Black", price: "399", condition: "excellent", description: "Latest GoPro with all accessories. Includes 3 batteries, mounts, and 128GB SD card." },
    { title: "Kindle Paperwhite Signature", price: "139", condition: "like-new", description: "32GB storage, wireless charging, auto-adjusting light. Includes leather cover." },
    { title: "Dyson V11 Vacuum Cleaner", price: "399", condition: "good", description: "Cordless stick vacuum with multiple attachments. Deep cleans carpets and hard floors." },
    { title: "Ring Video Doorbell Pro 2", price: "179", condition: "new", description: "Brand new, sealed in box. 1536p HD video, 3D motion detection, and Alexa integration." },
    { title: "Fitbit Charge 5", price: "119", condition: "excellent", description: "Advanced fitness tracker with built-in GPS. Black/Graphite. Tracks heart rate, sleep, stress." },
  ],
  
  Furniture: [
    { title: "Mid-Century Modern Sofa", price: "599", condition: "good", description: "Stylish 3-seater sofa in charcoal gray. Solid wood legs. Minor wear on armrests. Very comfortable." },
    { title: "Dining Table Set - 6 Chairs", price: "450", condition: "excellent", description: "Solid oak dining table with 6 upholstered chairs. Seats 8 people. Perfect for family dinners." },
    { title: "King Size Bed Frame", price: "299", condition: "good", description: "Sturdy wooden bed frame with headboard. Espresso finish. Easy assembly. Mattress not included." },
    { title: "Office Desk with Drawers", price: "189", condition: "excellent", description: "L-shaped corner desk with 3 drawers. White finish. Great for home office. Cable management included." },
    { title: "Leather Recliner Chair", price: "399", condition: "like-new", description: "Genuine leather power recliner in brown. Massage and heating functions. Like new condition." },
    { title: "Bookshelf - 5 Tier", price: "79", condition: "good", description: "Tall wooden bookshelf with 5 shelves. Walnut finish. Holds books, plants, and decor." },
    { title: "Coffee Table - Glass Top", price: "149", condition: "excellent", description: "Modern glass coffee table with chrome legs. Tempered glass top. No scratches." },
    { title: "Dresser - 6 Drawer", price: "229", condition: "good", description: "Solid wood dresser with 6 spacious drawers. White finish. Great storage solution." },
    { title: "Outdoor Patio Set", price: "499", condition: "excellent", description: "4-piece wicker patio furniture set. Includes sofa, 2 chairs, and coffee table. Weather-resistant cushions." },
    { title: "Bar Stools - Set of 2", price: "119", condition: "like-new", description: "Modern swivel bar stools with backs. Gray upholstery. Adjustable height. Barely used." },
    { title: "TV Stand - 65 inch", price: "179", condition: "good", description: "Entertainment center with storage shelves. Fits TVs up to 65\". Black finish." },
    { title: "Nightstand Pair", price: "99", condition: "excellent", description: "Set of 2 matching nightstands with drawers. Oak finish. Perfect for bedroom." },
    { title: "Accent Chair - Velvet", price: "249", condition: "like-new", description: "Luxurious emerald green velvet accent chair. Gold metal legs. Statement piece for any room." },
    { title: "Storage Ottoman", price: "89", condition: "good", description: "Large storage ottoman in gray fabric. Doubles as extra seating. Hidden storage inside." },
    { title: "Floor Lamp - Arc Design", price: "129", condition: "excellent", description: "Modern arc floor lamp with marble base. Adjustable height. Perfect for reading nook." },
  ],

  Clothing: [
    { title: "Men's Leather Jacket - L", price: "199", condition: "good", description: "Genuine leather motorcycle jacket. Size Large. Black. Classic style with zipper pockets." },
    { title: "Women's Winter Coat - M", price: "149", condition: "excellent", description: "North Face puffer coat in navy blue. Size Medium. Down-filled, very warm. Like new." },
    { title: "Designer Jeans - Levi's 501", price: "59", condition: "good", description: "Classic Levi's 501 jeans. Size 32x32. Dark wash. Gently worn, no rips or stains." },
    { title: "Nike Air Max Sneakers - 10", price: "89", condition: "excellent", description: "Men's Nike Air Max 90 in white/black. Size 10. Worn twice. Original box included." },
    { title: "Formal Suit - Men's 42R", price: "249", condition: "like-new", description: "Hugo Boss navy blue suit. 42 Regular. Wool blend. Includes jacket and pants. Dry cleaned." },
    { title: "Summer Dress Collection", price: "79", condition: "excellent", description: "Bundle of 5 summer dresses. Sizes S-M. Various colors and styles. Perfect condition." },
    { title: "Cashmere Sweater - Women's", price: "89", condition: "good", description: "100% cashmere V-neck sweater. Size Small. Camel color. Soft and luxurious." },
    { title: "Running Shoes - Adidas", price: "69", condition: "good", description: "Adidas Ultraboost 21. Women's size 8. Gray/pink. Great cushioning for runners." },
    { title: "Vintage Band T-Shirts", price: "45", condition: "good", description: "Collection of 3 vintage concert tees. Sizes M-L. Bands: Pink Floyd, Led Zeppelin, The Doors." },
    { title: "Winter Boots - Timberland", price: "119", condition: "excellent", description: "Men's Timberland 6-inch premium boots. Size 11. Wheat color. Waterproof. Barely worn." },
    { title: "Yoga Pants - Lululemon", price: "59", condition: "like-new", description: "Lululemon Align leggings. Size 6. Black. High-waisted. Worn once." },
    { title: "Men's Watch - Fossil", price: "99", condition: "excellent", description: "Fossil chronograph watch with leather band. Stainless steel case. Keeps perfect time." },
    { title: "Handbag - Michael Kors", price: "149", condition: "good", description: "Authentic Michael Kors tote bag. Tan leather. Multiple compartments. Minor wear on handles." },
    { title: "Sunglasses - Ray-Ban", price: "89", condition: "excellent", description: "Ray-Ban Wayfarer sunglasses. Polarized lenses. Black frames. Includes case and cloth." },
    { title: "Scarf Collection - Designer", price: "69", condition: "good", description: "Set of 3 designer scarves. Silk and cashmere blend. Various patterns. Great for gifting." },
  ],

  Vehicles: [
    { title: "2018 Honda Civic EX", price: "18500", condition: "excellent", description: "One owner, 45k miles. Excellent condition. Sunroof, backup camera, Honda Sensing. Clean title." },
    { title: "2020 Toyota Camry SE", price: "22900", condition: "like-new", description: "Certified pre-owned. 28k miles. Sport package. Apple CarPlay. Remaining factory warranty." },
    { title: "2016 Ford F-150 XLT", price: "26500", condition: "good", description: "4WD, crew cab, 5.0L V8. 78k miles. Towing package. Bed liner. Well maintained." },
    { title: "2019 Mazda CX-5 Touring", price: "21900", condition: "excellent", description: "AWD SUV. 35k miles. Leather seats, heated seats, navigation. Non-smoker, garage kept." },
    { title: "2017 Subaru Outback", price: "19900", condition: "good", description: "AWD wagon. 62k miles. Perfect for outdoor adventures. Roof rack included. Service records available." },
    { title: "2021 Tesla Model 3", price: "38900", condition: "excellent", description: "Long Range AWD. 18k miles. Autopilot, premium interior. White exterior, black interior." },
    { title: "2015 Jeep Wrangler Unlimited", price: "27500", condition: "good", description: "4-door, 4WD. 85k miles. Lifted with 35\" tires. Hard top and soft top included." },
    { title: "2019 Hyundai Elantra", price: "14900", condition: "excellent", description: "Compact sedan. 42k miles. Great gas mileage. Bluetooth, backup camera. Clean Carfax." },
    { title: "2020 Kia Sorento SX", price: "26900", condition: "like-new", description: "7-passenger SUV. 22k miles. Leather, panoramic sunroof, AWD. Like new condition." },
    { title: "2016 BMW 3 Series 328i", price: "19900", condition: "good", description: "Luxury sedan. 68k miles. Sport package, navigation. Well maintained. Premium sound system." },
    { title: "Mountain Bike - Trek", price: "899", condition: "excellent", description: "Trek X-Caliber 8. 29\" wheels. Shimano components. Barely used. Perfect for trails." },
    { title: "Road Bike - Specialized", price: "1299", condition: "good", description: "Specialized Allez Sprint. Carbon fork. Shimano 105 groupset. Great for racing or fitness." },
    { title: "Electric Scooter - Segway", price: "499", condition: "excellent", description: "Segway Ninebot Max. 40-mile range. Folds for transport. Barely used." },
    { title: "Kayak - Ocean Fishing", price: "799", condition: "good", description: "12-foot fishing kayak. Includes paddle, rod holders, and anchor. Stable and durable." },
    { title: "Motorcycle - Harley Sportster", price: "7900", condition: "good", description: "2014 Harley-Davidson Sportster 883. 12k miles. Custom exhaust. Runs great." },
  ],

  Services: [
    { title: "Professional Photography", price: "299", condition: "new", description: "Event and portrait photography services. 2-hour session with edited photos. Weddings, family, corporate." },
    { title: "Home Cleaning Service", price: "120", condition: "new", description: "Deep cleaning for 2-3 bedroom homes. Eco-friendly products. Experienced and insured team." },
    { title: "Lawn Care & Landscaping", price: "75", condition: "new", description: "Weekly lawn mowing and edging. Seasonal cleanup available. Serving local area for 10 years." },
    { title: "Personal Training Sessions", price: "60", condition: "new", description: "Certified personal trainer. One-on-one or group sessions. Customized workout plans." },
    { title: "Tutoring - Math & Science", price: "45", condition: "new", description: "Experienced tutor for high school and college students. Algebra, calculus, physics, chemistry." },
    { title: "Pet Sitting & Dog Walking", price: "35", condition: "new", description: "Reliable pet care while you're away. Daily walks, feeding, playtime. References available." },
    { title: "Handyman Services", price: "85", condition: "new", description: "General home repairs and maintenance. Plumbing, electrical, drywall, painting. Licensed and insured." },
    { title: "Web Design & Development", price: "1500", condition: "new", description: "Custom website design and development. Responsive, SEO-optimized. Portfolio available." },
    { title: "Piano Lessons", price: "50", condition: "new", description: "Private piano instruction for all ages and skill levels. Classical and contemporary styles." },
    { title: "Auto Detailing", price: "150", condition: "new", description: "Complete interior and exterior detailing. Hand wash, wax, vacuum, leather treatment." },
    { title: "Tax Preparation", price: "200", condition: "new", description: "Professional tax preparation for individuals and small businesses. CPA with 15 years experience." },
    { title: "Moving Services", price: "400", condition: "new", description: "Local moving services. 2 movers and truck for 4 hours. Careful handling of your belongings." },
    { title: "Massage Therapy", price: "90", condition: "new", description: "Licensed massage therapist. Swedish, deep tissue, sports massage. 60-minute sessions." },
    { title: "Computer Repair", price: "75", condition: "new", description: "PC and Mac repair. Virus removal, hardware upgrades, data recovery. Same-day service available." },
    { title: "Event DJ Services", price: "500", condition: "new", description: "Professional DJ for weddings, parties, corporate events. Full sound system and lighting included." },
  ],
};

export const locations = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "Fort Worth, TX",
  "Columbus, OH",
  "Charlotte, NC",
  "San Francisco, CA",
  "Indianapolis, IN",
  "Seattle, WA",
  "Denver, CO",
  "Boston, MA",
];

// Placeholder images from Unsplash (free to use)
export const categoryImages: Record<string, string[]> = {
  Electronics: [
    "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800",
    "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800",
    "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
  ],
  Furniture: [
    "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
    "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800",
    "https://images.unsplash.com/photo-1538688423619-a81d3f23454b?w=800",
    "https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800",
  ],
  Clothing: [
    "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800",
    "https://images.unsplash.com/photo-1445205170230-053b83016050?w=800",
    "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800",
    "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=800",
  ],
  Vehicles: [
    "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800",
    "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800",
    "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800",
  ],
  Services: [
    "https://images.unsplash.com/photo-1556740758-90de374c12ad?w=800",
    "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800",
    "https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=800",
    "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800",
  ],
};

